name: C/C++ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
    steps:
    - uses: actions/checkout@v3
    - name: config
      if: ${{matrix.os=='windows-latest'}}
      shell: cmd
      run: |
        dir /b "C:/"'
        '"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"'
    - name: make
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: make -f makeLinux
    - name: make
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      env:
        cxx: clang
      run: make -f makeWindows
    - name: make test
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: make -f makeLinux test
    - name: make test
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      run: make -f makeWindows test
