name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - name: Run eslint
      run: npm run lint
    - name: Enable Developer Command Prompt (amd64)
      uses: ./
      with:
        arch: amd64
    - uses: actions/checkout@v3
    - name: make
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: make -f makeLinux
    - name: make
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      run: make -f makeWindows
    - name: make test
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: make -f makeLinux test
    - name: make test
      if: ${{ matrix.os == 'windows-latest' }}
      shell: cmd
      run: make -f makeWindows test
